runserver:
	poetry run python manage.py runserver

app:
	poetry run python manage.py startapp $(name)

migrate:
	poetry run python manage.py migrate

makemigrations:
	poetry run python manage.py makemigrations